site_name: counter_review_logic
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: counter_review_logic
      handlers:
        python:
          options:
            docstring_style: numpy